"""add null-safe indexes, reverse-lookup indexes, timestamps, and calculation status

Revision ID: e50de3129c84
Revises: faa9f50bc029
Create Date: 2026-07-22 23:00:01.762231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e50de3129c84'
down_revision: Union[str, Sequence[str], None] = 'faa9f50bc029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('calculation', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('calculation', sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='calcstatus'), nullable=True))
    op.add_column('calculation', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index('ix_calculation_geometry_link_calculation_id', 'calculation_geometry_link', ['calculation_id'], unique=False)
    op.create_index('ix_calculation_trajectory_link_calculation_id', 'calculation_trajectory_link', ['calculation_id'], unique=False)
    op.add_column('energy', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('energy', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('geometry', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('geometry', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('gradient', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('gradient', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('hessian', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('hessian', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('identity', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('identity', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('identity_extras', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('identity_extras', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index(op.f('ix_identity_extras_identity_id'), 'identity_extras', ['identity_id'], unique=False)
    op.add_column('model', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('model', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # Autogenerate can't reflect SQLite expression-based indexes, so this and
    # 'unq_step_stages_null_safe' below aren't detected/created automatically.
    op.create_index(
        'unique_model_null_safe',
        'model',
        [
            'program',
            sa.text("coalesce(program_version, '')"),
            'method',
            sa.text("coalesce(basis, '')"),
        ],
        unique=True,
    )
    op.add_column('stage', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('stage', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index('ix_stationary_identity_link_identity_id', 'stationary_identity_link', ['identity_id'], unique=False)
    op.add_column('stationary_point', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('stationary_point', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index('ix_stationary_stage_link_stage_id', 'stationary_stage_link', ['stage_id'], unique=False)
    op.add_column('step', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('step', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index('ix_step_stage_id1', 'step', ['stage_id1'], unique=False)
    op.create_index('ix_step_stage_id2', 'step', ['stage_id2'], unique=False)
    op.create_index('ix_step_stage_id_ts', 'step', ['stage_id_ts'], unique=False)
    op.create_index(
        'unq_step_stages_null_safe',
        'step',
        ['stage_id1', 'stage_id2', sa.text('coalesce(stage_id_ts, 0)')],
        unique=True,
    )
    op.create_index('ix_step_validation_link_validation_id', 'step_validation_link', ['validation_id'], unique=False)
    op.add_column('trajectory', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('trajectory', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index('ix_trajectory_geometry_link_trajectory_id', 'trajectory_geometry_link', ['trajectory_id'], unique=False)
    op.add_column('validation', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('validation', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.alter_column('validation', 'calculation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_validation_calculation_id'), 'validation', ['calculation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_calculation_id'), table_name='validation')
    op.alter_column('validation', 'calculation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('validation', 'updated_at')
    op.drop_column('validation', 'created_at')
    op.drop_index('ix_trajectory_geometry_link_trajectory_id', table_name='trajectory_geometry_link')
    op.drop_column('trajectory', 'updated_at')
    op.drop_column('trajectory', 'created_at')
    op.drop_index('ix_step_validation_link_validation_id', table_name='step_validation_link')
    op.drop_index('unq_step_stages_null_safe', table_name='step')
    op.drop_index('ix_step_stage_id_ts', table_name='step')
    op.drop_index('ix_step_stage_id2', table_name='step')
    op.drop_index('ix_step_stage_id1', table_name='step')
    op.drop_column('step', 'updated_at')
    op.drop_column('step', 'created_at')
    op.drop_index('ix_stationary_stage_link_stage_id', table_name='stationary_stage_link')
    op.drop_column('stationary_point', 'updated_at')
    op.drop_column('stationary_point', 'created_at')
    op.drop_index('ix_stationary_identity_link_identity_id', table_name='stationary_identity_link')
    op.drop_column('stage', 'updated_at')
    op.drop_column('stage', 'created_at')
    op.drop_index('unique_model_null_safe', table_name='model')
    op.drop_column('model', 'updated_at')
    op.drop_column('model', 'created_at')
    op.drop_index(op.f('ix_identity_extras_identity_id'), table_name='identity_extras')
    op.drop_column('identity_extras', 'updated_at')
    op.drop_column('identity_extras', 'created_at')
    op.drop_column('identity', 'updated_at')
    op.drop_column('identity', 'created_at')
    op.drop_column('hessian', 'updated_at')
    op.drop_column('hessian', 'created_at')
    op.drop_column('gradient', 'updated_at')
    op.drop_column('gradient', 'created_at')
    op.drop_column('geometry', 'updated_at')
    op.drop_column('geometry', 'created_at')
    op.drop_column('energy', 'updated_at')
    op.drop_column('energy', 'created_at')
    op.drop_index('ix_calculation_trajectory_link_calculation_id', table_name='calculation_trajectory_link')
    op.drop_index('ix_calculation_geometry_link_calculation_id', table_name='calculation_geometry_link')
    op.drop_column('calculation', 'error_message')
    op.drop_column('calculation', 'status')
    op.drop_column('calculation', 'updated_at')
    op.drop_column('calculation', 'created_at')
    # ### end Alembic commands ###
