"""baseline: current schema

Revision ID: faa9f50bc029
Revises: 
Create Date: 2026-07-22 22:49:12.069197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

import autostorage.types


# revision identifiers, used by Alembic.
revision: str = 'faa9f50bc029'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.Column('coordinates', autostorage.types.CompressedArrayTypeDecorator(), nullable=True),
    sa.Column('charge', sa.Integer(), nullable=False),
    sa.Column('spin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity',
    sa.Column('algorithm', sa.Enum('RDKIT_INCHI', 'RDKIT_SMILES', 'IRMSD', name='algorithm'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'algorithm', 'value', name='unique_identity')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('program_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('basis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program', 'program_version', 'method', 'basis', name='unique_model')
    )
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_ts', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trajectory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('calc_type', sa.Enum('optimization', 'transition_optimization', 'conformer_search', 'scan', 'intrinsic_reaction_coordinate', 'minimum_energy_path_search', 'energy', 'gradient', 'frequency', 'thermochemistry', 'undefined', name='calctype'), nullable=True),
    sa.Column('input_provenance', sa.JSON(), nullable=True),
    sa.Column('output_provenance', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_model_id'), 'calculation', ['model_id'], unique=False)
    op.create_table('identity_extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id1', sa.Integer(), nullable=False),
    sa.Column('stage_id2', sa.Integer(), nullable=False),
    sa.Column('stage_id_ts', sa.Integer(), nullable=True),
    sa.Column('is_barrierless', sa.Boolean(), nullable=False),
    sa.CheckConstraint('stage_id1 < stage_id2', name='chk_stage_order'),
    sa.ForeignKeyConstraint(['stage_id1'], ['stage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id2'], ['stage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id_ts'], ['stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id1', 'stage_id2', 'stage_id_ts', name='unq_step_stages')
    )
    op.create_table('trajectory_geometry_link',
    sa.Column('geometry_id', sa.Integer(), nullable=False),
    sa.Column('trajectory_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['geometry_id'], ['geometry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('geometry_id', 'trajectory_id')
    )
    op.create_table('calculation_geometry_link',
    sa.Column('geometry_id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('input', 'output', name='role'), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geometry_id'], ['geometry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('geometry_id', 'calculation_id')
    )
    op.create_table('calculation_trajectory_link',
    sa.Column('trajectory_id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('input', 'output', name='role'), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trajectory_id', 'calculation_id')
    )
    op.create_table('energy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geometry_id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geometry_id'], ['geometry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_calculation_id'), 'energy', ['calculation_id'], unique=False)
    op.create_index(op.f('ix_energy_geometry_id'), 'energy', ['geometry_id'], unique=False)
    op.create_table('gradient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geometry_id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('value', autostorage.types.CompressedArrayTypeDecorator(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geometry_id'], ['geometry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gradient_calculation_id'), 'gradient', ['calculation_id'], unique=False)
    op.create_index(op.f('ix_gradient_geometry_id'), 'gradient', ['geometry_id'], unique=False)
    op.create_table('hessian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geometry_id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('value', autostorage.types.CompressedArrayTypeDecorator(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geometry_id'], ['geometry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hessian_calculation_id'), 'hessian', ['calculation_id'], unique=False)
    op.create_index(op.f('ix_hessian_geometry_id'), 'hessian', ['geometry_id'], unique=False)
    op.create_table('stationary_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geometry_id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_pseudo', sa.Boolean(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geometry_id'], ['geometry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stationary_point_calculation_id'), 'stationary_point', ['calculation_id'], unique=False)
    op.create_index(op.f('ix_stationary_point_geometry_id'), 'stationary_point', ['geometry_id'], unique=False)
    op.create_table('validation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stationary_identity_link',
    sa.Column('stationary_id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stationary_id'], ['stationary_point.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stationary_id', 'identity_id')
    )
    op.create_table('stationary_stage_link',
    sa.Column('stationary_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stationary_id'], ['stationary_point.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stationary_id', 'stage_id')
    )
    op.create_table('step_validation_link',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('validation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_id'], ['validation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', 'validation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_validation_link')
    op.drop_table('stationary_stage_link')
    op.drop_table('stationary_identity_link')
    op.drop_table('validation')
    op.drop_index(op.f('ix_stationary_point_geometry_id'), table_name='stationary_point')
    op.drop_index(op.f('ix_stationary_point_calculation_id'), table_name='stationary_point')
    op.drop_table('stationary_point')
    op.drop_index(op.f('ix_hessian_geometry_id'), table_name='hessian')
    op.drop_index(op.f('ix_hessian_calculation_id'), table_name='hessian')
    op.drop_table('hessian')
    op.drop_index(op.f('ix_gradient_geometry_id'), table_name='gradient')
    op.drop_index(op.f('ix_gradient_calculation_id'), table_name='gradient')
    op.drop_table('gradient')
    op.drop_index(op.f('ix_energy_geometry_id'), table_name='energy')
    op.drop_index(op.f('ix_energy_calculation_id'), table_name='energy')
    op.drop_table('energy')
    op.drop_table('calculation_trajectory_link')
    op.drop_table('calculation_geometry_link')
    op.drop_table('trajectory_geometry_link')
    op.drop_table('step')
    op.drop_table('identity_extras')
    op.drop_index(op.f('ix_calculation_model_id'), table_name='calculation')
    op.drop_table('calculation')
    op.drop_table('trajectory')
    op.drop_table('stage')
    op.drop_table('model')
    op.drop_table('identity')
    op.drop_table('geometry')
    # ### end Alembic commands ###
